AL-5635: Create library for adapted signer
AlmaLinux/build-system-signer pull request #1
Opened 2024-11-26 17:21 UTC by maccelf

2024-11-27 11:47 UTC, anfimovdm requested changes
Also, please add type annotations

2024-11-27 11:47 UTC, anfimovdm commented on src/signer/base_signer.py
> +    WRONG_SIGNATURE = 4
Please move it into constants.py

2024-11-27 11:47 UTC, anfimovdm commented on src/signer/base_signer.py
> +class BaseSigner(object):
No need to inherit from object here

2024-11-27 11:47 UTC, anfimovdm commented on src/signer/base_signer.py
> +            if not os.path.exists(pkg_path):
We can use pathlib module instead

2024-11-27 11:47 UTC, anfimovdm commented on src/signer/base_signer.py
> +        def check(pkg_path: str) -> typing.Tuple[SignStatusEnum, str]:
It could be a staticmethod

2024-11-27 11:47 UTC, anfimovdm commented on src/signer/base_signer.py
> +                futures[executor.submit(check, file_)] = file_
Could be a dict comprehension

2024-11-27 11:47 UTC, anfimovdm commented on src/signer/base_signer.py
> +            with ThreadPoolExecutor(max_workers=4) as executor:
Please move that part in try-except block into a separate func

2024-11-27 11:47 UTC, anfimovdm commented on src/signer/errors.py
> +        super(CommandExecutionError, self).__init__(message)
No need to pass arguments to super method

2024-11-27 11:47 UTC, anfimovdm commented on src/signer/package_sign.py
> +def _unpack_ar_file(ar_path, file_name, stdout):
I think we should discuss it first with our release managers, maybe we don't need to sign deb-like packages at all

2024-11-28 17:02 UTC, maccelf commented
Closed because of https://github.com/AlmaLinux/build-system-common-library/pull/1

2024-11-28 17:02 UTC, closed without merging